from ticket.models import Tickets
from ticket.models import User
from ticket.models import Categories
from ticket.models import Role
from ticket.models import Division
from ticket.models import District
from ticket.models import City
from ticket.models import TicketStatus
from ticket.models import ResponseStatus
from ticket.models import TicketResponse
from ticket.models import Zone
from ticket.models import Feedback
from ticket.models import SatisfactionStatus
