# Generated by Django 3.1.4 on 2026-03-24 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_responsestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_attended_by', models.CharField(max_length=255, null=True)),
                ('desigination', models.CharField(max_length=255, null=True)),
                ('response_status', models.CharField(max_length=255, null=True)),
                ('reported_by_field_staff', models.CharField(max_length=255, null=True)),
                ('response_added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_ticket_reponse',
            },
        ),
    ]
