# Generated by Django 3.1.4 on 2026-03-24 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticketresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketresponse',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.tickets'),
        ),
    ]
