# Generated by Django 3.1.4 on 2026-03-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.zone'),
        ),
    ]
