# Generated by Django 3.1.4 on 2026-03-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_division_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='resolution_status',
            field=models.IntegerField(default=0),
        ),
    ]
