# Generated by Django 3.1.4 on 2026-03-25 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_tickets_resolution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketresponse',
            name='response_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.responsestatus'),
        ),
    ]
