# Generated by Django 3.1.4 on 2026-03-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20260325_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_status',
        ),
    ]
