# Generated by Django 3.1.4 on 2026-03-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_remove_tickets_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='plant_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
