# Generated by Django 3.1.4 on 2026-03-30 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20260325_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfacton_status', models.CharField(max_length=255, null=True)),
                ('remarks', models.TextField(null=True)),
                ('feedback_conducted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('feedback_conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.tickets')),
            ],
            options={
                'db_table': 'tbl_feedback',
            },
        ),
    ]
