# Generated by Django 3.1.4 on 2026-03-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_feedback_satisfaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='satisfacton_status',
        ),
    ]
