# Generated by Django 3.1.4 on 2026-03-30 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_remove_feedback_satisfacton_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='satisfaction_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.satisfactionstatus'),
        ),
    ]
