# Generated by Django 3.1.4 on 2026-03-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_tickets_satisfaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='satisfaction_status',
            field=models.IntegerField(default=0),
        ),
    ]
