# Generated by Django 3.1.4 on 2026-03-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_auto_20260330_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='satisfaction_status',
            new_name='satisfaction_status_on_feedback',
        ),
    ]
