# Generated by Django 3.1.4 on 2026-03-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_auto_20260330_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='satisfaction_status_on_feedback',
            field=models.IntegerField(null=True),
        ),
    ]
