# Generated by Django 3.1.4 on 2026-04-01 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_auto_20260330_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ticket_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticketresponse'),
        ),
    ]
