# Generated by Django 3.1.4 on 2026-04-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_feedback_ticket_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='complainant_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
