# Generated by Django 3.1.4 on 2026-04-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0020_auto_20260401_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='zone',
            field=models.IntegerField(default=1),
        ),
    ]
