# Generated by Django 3.1.4 on 2026-04-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_role_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='zone',
            field=models.IntegerField(default=0),
        ),
    ]
