# Generated by Django 3.1.4 on 2026-04-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0022_auto_20260402_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='zone',
        ),
        migrations.AddField(
            model_name='user',
            name='zone_id',
            field=models.IntegerField(default=0),
        ),
    ]
