# Generated by Django 3.1.4 on 2026-04-06 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_auto_20260402_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.zone'),
        ),
    ]
